# Generated by Django 5.1 on 2025-01-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userachievement',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='userindustry',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='usermilestone',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userindustry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermilestone',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='categories',
            field=models.ManyToManyField(blank=True, to='users.category'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='industry',
            field=models.CharField(choices=[('EDUCATION', 'Education'), ('HEALTHCARE', 'Healthcare'), ('CYBER_SECURITY', 'Cyber Security'), ('SOFTWARE_ENGINEERING', 'Software Engineering'), ('DATA_SCIENCE', 'Data Science'), ('FINANCE', 'Finance'), ('AI', 'AI'), ('ENERGY', 'Energy'), ('TRANSPORTATION', 'Transportation'), ('VIDEO_GAME_DEV', 'Video Game Development'), ('GOVERNMENT', 'Government'), ('MEDIA_ENTERTAINMENT', 'Media & Entertainment'), ('STARTUP', 'Startup'), ('NON_PROFIT', 'Non-Profit')], default='SOFTWARE_ENGINEERING', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='milestones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.ManyToManyField(blank=True, to='users.skill'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(choices=[('PERTH', 'Perth'), ('ADELAIDE', 'Adelaide'), ('MELBOURNE', 'Melbourne'), ('HOBART', 'Hobart'), ('CANBERRA', 'Canberra'), ('SYDNEY', 'Sydney'), ('BRISBANE', 'Brisbane'), ('DARWIN', 'Darwin')], default='PERTH', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
        migrations.DeleteModel(
            name='UserAchievement',
        ),
        migrations.DeleteModel(
            name='UserCategory',
        ),
        migrations.DeleteModel(
            name='UserIndustry',
        ),
        migrations.DeleteModel(
            name='UserLocation',
        ),
        migrations.DeleteModel(
            name='UserMilestone',
        ),
        migrations.DeleteModel(
            name='UserSkill',
        ),
    ]
