# Generated by Django 5.1.5 on 2025-01-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_categories_alter_customuser_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, choices=[('PERTH', 'Perth'), ('ADELAIDE', 'Adelaide'), ('MELBOURNE', 'Melbourne'), ('HOBART', 'Hobart'), ('CANBERRA', 'Canberra'), ('SYDNEY', 'Sydney'), ('BRISBANE', 'Brisbane'), ('DARWIN', 'Darwin')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='skills',
            field=models.ManyToManyField(blank=True, to='users.skill'),
        ),
    ]
