# Generated by Django 5.1 on 2025-01-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('industry', models.CharField(choices=[('SOFTWARE_ENGINEERING', 'Software Engineering'), ('EDUCATION', 'Education'), ('HEALTHCARE', 'Healthcare'), ('BUSINESS', 'Business'), ('ARTS', 'Arts'), ('OTHER', 'Other')], max_length=50)),
                ('current_role', models.CharField(max_length=255)),
                ('why_inspiring', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
