# Generated by Django 5.1 on 2025-01-29 09:05

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 9, 5, 10, 45679, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitation',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='industry',
            field=models.CharField(choices=[('SOFTWARE_ENGINEERING', 'Software Engineering'), ('EDUCATION', 'Education'), ('HEALTHCARE', 'Healthcare'), ('BUSINESS', 'Business'), ('ARTS', 'Arts'), ('OTHER', 'Other')], max_length=100),
        ),
        migrations.AlterModelTable(
            name='invitation',
            table='invitations',
        ),
    ]
